version: '3.9'
services:
  api:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: axion
      POSTGRES_PASSWORD: axion
      POSTGRES_DB: axion
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
